apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: qubide-main
  labels: { app: api-gateway }
spec:
  replicas: 1
  selector:
    matchLabels: { app: api-gateway }
  template:
    metadata:
      labels: { app: api-gateway }
    spec:
      serviceAccountName: orchestrator-sa
      containers:
        - name: api-gateway
          image: prakashbanjade/cloud-ide-api-gateway:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef: { name: gateway-env }
          env:
            - name: PG_USER
              valueFrom: { secretKeyRef: { name: postgres-secret, key: POSTGRES_USER } }
            - name: PG_PWD
              valueFrom: { secretKeyRef: { name: postgres-secret, key: POSTGRES_PASSWORD } }
            - name: PG_DB
              valueFrom: { secretKeyRef: { name: postgres-secret, key: POSTGRES_DB } }
            - name: PG_HOST
              value: postgres
            - name: REDIS_URL
              value: redis://redis:6379
          ports:
            - containerPort: 3002
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
              ephemeral-storage: "2Gi"
            limits:
              cpu: "500m"
              memory: "1Gi"
              ephemeral-storage: "5Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: qubide-main
spec:
  selector: { app: api-gateway }
  ports:
    - name: api
      protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP

# =========================
# Ingress
# =========================
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
  namespace: qubide-main
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [ api-gateway.qubide.cloud ]
      secretName: api-gateway-tls
  rules:
    - host: api-gateway.qubide.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 3002
