apiVersion: v1
kind: Secret

metadata:
  name: runner-env
  namespace: qubide
type: Opaque
stringData:
  MINIO_ACCESS_KEY: secret
  MINIO_SECRET_KEY: very_secret
  MINIO_ENDPOINT: minio.minio-dev.svc.cluster.local
  MINIO_PORT: "9000"
  ACCESS_TOKEN_SECRET: very_secret
  ACCESS_TOKEN_EXPIRATION_SEC: "300"
  OPENAI_API_KEY: very_secret
  CLIENT_URL: "http://localhost:3000"
  GROQ_API_KEY: very_secret