apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: qubide-main
type: Opaque
stringData:
  POSTGRES_USER: postgres_user
  POSTGRES_PASSWORD: very_secret_change_in_production
  POSTGRES_DB: qubide_db